#!/bin/bash

echo "Welcome to Chakora's module retriever"
echo "Just sit back and relax for now, this will take a bit"

yes | cpan -if IO::Socket Sub::Delete Config::JSON Digest::Whirlpool Digest::HMAC Email::Valid

echo "Modules installed"
echo "Thanks for using Chakora :)"
